# Generated by Django 3.2.10 on 2021-12-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaType',
            new_name='Articles',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='name',
            new_name='title',
        ),
    ]
